### ISSUE TITLE
data class with interface and default implementation for getter will not render schema

### ISSUE THREAD

**Issue by vetm73** [ExpediaDotCom/graphql-kotlin#214]
Hi,

I'll ask this question here because I ran into this issue building a Kotlin GraphQL application and I searched a lot on the internet for a similar example but could not find it.

I would like to have data classes implement an interface and would like to have them a convenient getter for a Base64 encoded universal ID.

My interface:

```kotlin
package ee.seventythr.web.backend.domain

import com.expedia.graphql.annotations.GraphQLID
import graphql.relay.Relay

interface Base {
    @GraphQLID
    val _id: String?

    val id: String?
        get() = _id?.let { Relay().toGlobalId(this::class.toString(), it) }
}
```

And my data class:

```kotlin
package ee.seventythr.web.backend.domain

import com.expedia.graphql.annotations.GraphQLID
import org.springframework.data.annotation.Id
import org.springframework.data.mongodb.core.mapping.Document

@Document(collection = "for_company")
data class ForCompany(
    @Id
    @GraphQLID
    override val _id: String? = null,
    val name: String,
    val image: String
): Base
```

And my mutation:

```kotlin
@Component
class ForCompanyMutation(val forCompanyRepository: ForCompanyRepository) : Mutation {
    @Value("\${files.forCompany}")
    lateinit var imagePath: String

    private val logger by LoggerDelegate()

    @GraphQLDescription("add for company")
    fun addForCompany(input: UploadImage, @GraphQLContext context: MyGraphQLContext): ForCompany {
        // if (!context.authenticated) throw NotAuthorizedException("Mike")
        File(imagePath, input.filename).writeBytes(stringToByteArray(input.data))
        return save(
            ForCompany(
                    name = input.name,
                    image = "${imagePath.substringAfterLast("/")}/${input.filename}"
            ), forCompanyRepository
        )
    }
}

fun <T:Base> save(document: T, repository: MongoRepository<T, String>): T {
    val savedDocument = repository.save(document)
    return savedDocument
}
```

But when starting my spring boot application I get the following exception:

```
	... 47 common frames omitted
Caused by: graphql.schema.validation.InvalidSchemaException: invalid schema:
object type 'ForCompany' does not implement interface 'Base' because field 'id' is missing
	at graphql.schema.GraphQLSchema$Builder.build(GraphQLSchema.java:344) ~[graphql-java-11.0.jar:na]
	at com.expedia.graphql.generator.SchemaGenerator.generate$graphql_kotlin(SchemaGenerator.kt:57) ~[graphql-kotlin-0.2.6.jar:na]
	at com.expedia.graphql.ToSchemaKt.toSchema(toSchema.kt:23) ~[graphql-kotlin-0.2.6.jar:na]
	at ee.seventythr.web.backend.configuration.GraphQL.schema(GraphQL.kt:58) ~[classes/:na]
	at ee.seventythr.web.backend.configuration.GraphQL$$EnhancerBySpringCGLIB$$71f0851e.CGLIB$schema$0(<generated>) ~[classes/:na]
	at ee.seventythr.web.backend.configuration.GraphQL$$EnhancerBySpringCGLIB$$71f0851e$$FastClassBySpringCGLIB$$f989bb65.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at ee.seventythr.web.backend.configuration.GraphQL$$EnhancerBySpringCGLIB$$71f0851e.schema(<generated>) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	... 48 common frames omitted

Disconnected from the target VM, address: '127.0.0.1:58404', transport: 'socket'

Process finished with exit code 1
```

When I move the default getter to the data class itself it works but I would like to define it in the interface so all my classes can use it.

I am doing something wrong but can not find relevant examples to learn from so I hope somebody can help me out.

Thanks in advance,

Mike

**Comment by brennantaylor** [comment]
It may be because the interface generation isn't smart enough to handle fields with default implementations. It's not clear how to resolve this in the library after only thinking for a few minutes about it.

Maybe as a work around for now what if you make `Base.id` an extension property instead to hide it from the generation if you don't need `id` in the final schema?

```kotlin
interface Base {
    @GraphQLID
    val _id: String?
}

val Base.id: String? = _id?.let { Relay().toGlobalId(this::class.toString(), it) }
```

**Comment by brennantaylor** [comment]
Another option (didn't check if it compiles) to work around may be to override `id` in `ForCompany`

```kotlin
data class ForCompany (...) : Base {
    override id = (this as Base).id // or however you get the "super" value 🤷‍♂ 
}
```

**Comment by vetm73** [comment]
Hi Brennan,

Thanks for pointing me in a direction. I ended up doing:

interface Base {
    @GraphQLID
    val _id: String?

    val id: String?
        get() = _id?.let { Relay().toGlobalId(this::class.toString(), it) }
}

And in the data class:

@Document(collection = "for_company")
data class ForCompany(
    @Id
    @GraphQLID
    override val _id: String? = null,
    val name: String,
    val image: String
): Base {
    override val id: String?
        get() = super.id
}
Kind regards,

Mike

**Comment by smyrick** [comment]
Closing as resolved
