### ISSUE TITLE
GraphQLInterfaceType is not support in willAddGraphQLTypeToSchema

### ISSUE THREAD

**Issue by smyrick** [ExpediaDotCom/graphql-kotlin#281]
**Library Version**
0.6.1

**Describe the bug**
`GraphQLInterfaceType` is not supported for the `willAddGraphQLTypeToSchema` hook

**To Reproduce**
```kotlin
// Hook function
override fun willAddGraphQLTypeToSchema(type: KType, generatedType: GraphQLType): GraphQLType {
        return when (generatedType) {
            is GraphQLInterfaceType -> GraphQLInterfaceType.newInterface(generatedType)
                .description("My resolved description").build()
            else -> generatedType
        }
    }
```

Produces this error
```
graphql.AssertException: All types within a GraphQL schema must have unique names. No two provided types may have the same name.
No provided type may have a name which conflicts with any built in types (including Scalar and Introspection types).
You have redefined the type 'Result' from being a 'GraphQLInterfaceType' to a 'GraphQLInterfaceType'

	at graphql.schema.GraphQLTypeCollectingVisitor.assertTypeUniqueness(GraphQLTypeCollectingVisitor.java:105)
	at graphql.schema.GraphQLTypeCollectingVisitor.visitGraphQLInterfaceType(GraphQLTypeCollectingVisitor.java:58)
	at graphql.schema.GraphQLInterfaceType.accept(GraphQLInterfaceType.java:152)
	at graphql.schema.TypeTraverser$TraverserDelegateVisitor.enter(TypeTraverser.java:71)
	at graphql.util.Traverser.traverse(Traverser.java:147)
	at graphql.schema.TypeTraverser.doTraverse(TypeTraverser.java:58)
	at graphql.schema.TypeTraverser.depthFirst(TypeTraverser.java:50)
	at graphql.schema.TypeTraverser.depthFirst(TypeTraverser.java:38)
	at graphql.schema.SchemaUtil.allTypes(SchemaUtil.java:42)
	at graphql.schema.GraphQLSchema.<init>(GraphQLSchema.java:102)
	at graphql.schema.GraphQLSchema.<init>(GraphQLSchema.java:37)
	at graphql.schema.GraphQLSchema$Builder.build(GraphQLSchema.java:411)
	at com.expedia.graphql.generator.SchemaGenerator.generate$graphql_kotlin_schema_generator(SchemaGenerator.kt:68)
	at com.expedia.graphql.ToSchemaKt.toSchema(toSchema.kt:24)
	at com.expedia.graphql.ToSchemaKt.toSchema$default(toSchema.kt:21)
```

**Expected behavior**
We can override the type of an interface with a hook

**Comment by dkuc84** [comment]
`didGenerateGraphQLType` hook is also broken for both interfaces and objects

```
    override fun didGenerateGraphQLType(type: KType, generatedType: GraphQLType): GraphQLType {
        return when (generatedType) {
            is GraphQLInterfaceType -> GraphQLInterfaceType.newInterface(generatedType)
                .description("My custom description").build()
            is GraphQLObjectType -> GraphQLObjectType.newObject(generatedType)
                .description("My custom description").build()
            else -> generatedType
        }
    }
```

This is due to the way `graphql-java` builds schema graph -> none of those objects implement hashcode/equals. Meaning that if you attempt to recreate a type that is already referenced then you end up with multiple objects with same name.

We could potentially change those hooks to work against builders instead of generated types.

**Comment by dkuc84** [comment]
Underlying issue here is that when building interfaces we also build out the types (which will reference it) and only then run the `willX` hook. This means that if you attempt to update the interface you will effectively be creating new interface but all the types would still reference the old one.
