### ISSUE TITLE
ClassCastException: kotlin.reflect.jvm.internal.KTypeParameterImpl cannot be cast to kotlin.reflect.KClass

### ISSUE THREAD

**Issue by mihbor** [ExpediaDotCom/graphql-kotlin#71]
A method with a signature that contains nested type parameters:

``` fun monthlyBreakdown(): List<Pair<String, Totals>>? {```
 
causes the library to throw a 

```
java.lang.ClassCastException: kotlin.reflect.jvm.internal.KTypeParameterImpl cannot be cast to kotlin.reflect.KClass
	at com.expedia.graphql.schema.generator.TypesCache.getKClassFromKType(TypesCache.kt:64)
	at com.expedia.graphql.schema.generator.TypesCache.getCacheKeyString(TypesCache.kt:48)
	at com.expedia.graphql.schema.generator.TypesCache.get(TypesCache.kt:23)
	at com.expedia.graphql.schema.generator.SchemaGenerator.objectFromReflection(SchemaGenerator.kt:197)
	at com.expedia.graphql.schema.generator.SchemaGenerator.graphQLTypeOf(SchemaGenerator.kt:189)
	at com.expedia.graphql.schema.generator.SchemaGenerator.graphQLTypeOf$default(SchemaGenerator.kt:187)
	at com.expedia.graphql.schema.generator.SchemaGenerator.property(SchemaGenerator.kt:154)
	at com.expedia.graphql.schema.generator.SchemaGenerator.objectType(SchemaGenerator.kt:270)
	at com.expedia.graphql.schema.generator.SchemaGenerator.objectType$default(SchemaGenerator.kt:243)
	at com.expedia.graphql.schema.generator.SchemaGenerator.getGraphQLType(SchemaGenerator.kt:217)
	at com.expedia.graphql.schema.generator.SchemaGenerator.objectFromReflection(SchemaGenerator.kt:204)
	at com.expedia.graphql.schema.generator.SchemaGenerator.graphQLTypeOf(SchemaGenerator.kt:189)
	at com.expedia.graphql.schema.generator.SchemaGenerator.listType(SchemaGenerator.kt:241)
	at com.expedia.graphql.schema.generator.SchemaGenerator.getGraphQLType(SchemaGenerator.kt:214)
	at com.expedia.graphql.schema.generator.SchemaGenerator.objectFromReflection(SchemaGenerator.kt:204)
	at com.expedia.graphql.schema.generator.SchemaGenerator.graphQLTypeOf(SchemaGenerator.kt:189)
	at com.expedia.graphql.schema.generator.SchemaGenerator.graphQLTypeOf$default(SchemaGenerator.kt:187)
	at com.expedia.graphql.schema.generator.SchemaGenerator.function(SchemaGenerator.kt:149)
	at com.expedia.graphql.schema.generator.SchemaGenerator.function$default(SchemaGenerator.kt:113)
	at com.expedia.graphql.schema.generator.SchemaGenerator.objectType(SchemaGenerator.kt:273)
	at com.expedia.graphql.schema.generator.SchemaGenerator.objectType$default(SchemaGenerator.kt:243)
	at com.expedia.graphql.schema.generator.SchemaGenerator.getGraphQLType(SchemaGenerator.kt:217)
	at com.expedia.graphql.schema.generator.SchemaGenerator.objectFromReflection(SchemaGenerator.kt:204)
	at com.expedia.graphql.schema.generator.SchemaGenerator.graphQLTypeOf(SchemaGenerator.kt:189)
	at com.expedia.graphql.schema.generator.SchemaGenerator.graphQLTypeOf$default(SchemaGenerator.kt:187)
	at com.expedia.graphql.schema.generator.SchemaGenerator.function(SchemaGenerator.kt:149)
	at com.expedia.graphql.schema.generator.SchemaGenerator.function$default(SchemaGenerator.kt:113)
	at com.expedia.graphql.schema.generator.SchemaGenerator.addQueries(SchemaGenerator.kt:87)
	at com.expedia.graphql.schema.generator.SchemaGenerator.generateWithReflection(SchemaGenerator.kt:66)
	at com.expedia.graphql.schema.generator.SchemaGenerator.generate$graphql_kotlin(SchemaGenerator.kt:60)
	at com.expedia.graphql.ToSchemaKt.toSchema(toSchema.kt:23)
	at com.expedia.graphql.ToSchemaKt.toSchema$default(toSchema.kt:17)
```

as a workaround, the following works as expected:

```
class Bucket(val key:String, val totals:Totals)
fun monthlyBreakdown(): List<Bucket>? {
```

**Comment by dkuc84** [comment]
Hello! Thanks for raising this issue but currently we won't be addressing it. Kotlin `Pair` is a very generic type that I don't think we should support. Your example could be further expanded with additional nesting of the objects -> e.g. consider deeply nested 'Pair' of 'Pair' of 'Pair'... of 'Pair' objects (or List of Lists for that matter) and the resulting schema. While this certainly could be supported, we believe this would also lead to a poor schema design and generally should be discouraged. 

Per GraphQL spec we should be using some specific types (like `Bucket` in your example) instead. It's the same reason why GraphQL spec does not specify generic `Map` type and requires explicit types.
